---
- hosts: build_host
  become: yes
  gather_facts: no
  tasks:
    - name: Create build directory
      file:
        path: /docker_build
        state: directory
        owner: root
        group: root
        mode: 0775
    - name: Copy build directory
      copy:
        src: ./files/docker/speedtest
        dest: /docker_build
        owner: root
        group: root
        mode: 0777
    - name: Build speedtest container image
      docker_image:
        name: speedtest
        build:
          path: /docker_build/speedtest
        source: build
        state: present
    # - name: Archive container image as a tarball
    #   docker_image:
    #     name: speedtest
    #     archive_path: /docker_build/speedtest_image.tar
    #     source: pull
    #     state: present
    # - name: Fetch archived image
    #   fetch:
    #     src: /docker_build/speedtest_image.tar
    #     dest: ./tmp/speedtest_image.tar
    #     flat: true        
    # - name: Copy tarball to host
    #   copy:
    #     src: ./tmp/speedtest_image.tar
    #     dest: /root/speedtest_image.tar
    # - name: Load container from tarball
    #   docker_image:
    #     name: speedtest
    #     load_path: /root/speedtest_image.tar
    #     state: present
    #     source: load