---
- hosts: server
  become: yes
  tasks:
  - name: Run apt update
    apt:
      update_cache: yes
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

# Install the requirements on server
- hosts: server
  become: yes
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose
  vars_files:
    - vars/all.yml
  roles:
    - geerlingguy.pip
    - geerlingguy.docker

# Install the docker-compose deployments
- hosts: server
  tags: deploy
  become: yes
  vars_files:
    - vars/all.yml

  tasks: 
    - name: Create docker/monitoring directory
      file:
        path: "{{ docker_monitoring_dir }}"
        state: directory
        owner: root
        group: root
        mode: 0777

    - name: Create data directory for grafana
      file:
        path: "{{ docker_monitoring_dir }}/grafana/data/"
        state: directory
        owner: root
        group: root
        mode: 0777

    - name: Copy grafana provisioning directory
      copy:
        src: files/grafana/provisioning
        dest: "{{ docker_monitoring_dir }}/grafana"
        
    - name: Copy docker-compose file (template based)
      template:
        src: files/docker-compose.yml
        dest: "{{ docker_monitoring_dir }}/"
        owner: root
        group: root
        mode: 0644

    # Copy the entire speedtest sources & the Dockerfile
    # Create the directory first?
    - name: Copy speedtest sources and Dockerfile
      copy:
        src: files/docker/speedtest
        dest: "{{ docker_monitoring_dir }}/docker"

    - name: Create and start services
      community.docker.docker_compose: 
        state: present
        restarted: yes
        project_src: "{{ docker_monitoring_dir }}/"
        build: yes
        recreate: always
        debug: yes
        remove_orphans: yes
      register: output

    - ansible.builtin.debug:
        var: output

